server:
 port: 8888
spring:
 application:
  name: cloud-config-server
# profiles:
#  active: native
 cloud:
  config:
   server:
    git:
     uri: https://github.com/sachin19927/HSM-config.git
     clone-on-start: true
     search-paths: configuration
     default-label: master
#     username: ${GIT_USERNAME}
#     password: ${GIT_PASSWORD}
#    native:
#     search-locations: classpath:configuration
